# Generated by Django 5.1.6 on 2025-03-06 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0002_authorizeduser_userprofile_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('intrusion', 'Intrusion Attempt'), ('blacklist', 'Blacklisted Entry'), ('watchlist', 'Watchlisted Entry'), ('overstay', 'Visitor Overstay'), ('visitor_registered', 'New Visitor Registered')], max_length=20, verbose_name='Alert Type')),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('authorized', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recognition.userprofile')),
            ],
        ),
    ]
