# Generated by Django 5.1.6 on 2025-03-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('stream_url', models.URLField()),
                ('camera_type', models.CharField(choices=[('IP Camera', 'IP Camera'), ('Webcam', 'Webcam'), ('CCTV', 'CCTV')], max_length=50)),
                ('face_recognition', models.BooleanField(default=False)),
                ('motion_detection', models.BooleanField(default=False)),
                ('night_vision', models.CharField(choices=[('auto', 'Auto'), ('on', 'Always On'), ('off', 'Always Off')], default='auto', max_length=10)),
                ('recording_mode', models.CharField(choices=[('continuous', 'Continuous'), ('motion-based', 'Motion-based'), ('manual', 'Manual')], default='motion-based', max_length=20)),
                ('storage', models.CharField(default='local', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='FaceData',
        ),
    ]
