# Generated by Django 5.1.6 on 2025-03-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_camera_delete_facedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='storage',
        ),
    ]
