# Generated by Django 5.1.6 on 2025-03-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_remove_camera_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='storage',
            field=models.CharField(default='local', max_length=50),
        ),
    ]
